%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clearvars -global
clear_persistent_variables(fileparts(which('dynare')), false)
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info
options_ = [];
M_.fname = 'Gali_2015_chapter_2';
M_.dynare_version = '6.2';
oo_.dynare_version = '6.2';
options_.dynare_version = '6.2';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(3,1);
M_.exo_names_tex = cell(3,1);
M_.exo_names_long = cell(3,1);
M_.exo_names(1) = {'eps_a'};
M_.exo_names_tex(1) = {'{\varepsilon_a}'};
M_.exo_names_long(1) = {'technology shock'};
M_.exo_names(2) = {'eps_z'};
M_.exo_names_tex(2) = {'{\varepsilon_z}'};
M_.exo_names_long(2) = {'preference shock'};
M_.exo_names(3) = {'eps_nu'};
M_.exo_names_tex(3) = {'{\varepsilon_\nu}'};
M_.exo_names_long(3) = {'monetary policy shock'};
M_.endo_names = cell(12,1);
M_.endo_names_tex = cell(12,1);
M_.endo_names_long = cell(12,1);
M_.endo_names(1) = {'C'};
M_.endo_names_tex(1) = {'{C}'};
M_.endo_names_long(1) = {'Consumption'};
M_.endo_names(2) = {'W_real'};
M_.endo_names_tex(2) = {'{\frac{W}{P}}'};
M_.endo_names_long(2) = {'Real Wage'};
M_.endo_names(3) = {'Pi'};
M_.endo_names_tex(3) = {'{\Pi}'};
M_.endo_names_long(3) = {'inflation'};
M_.endo_names(4) = {'A'};
M_.endo_names_tex(4) = {'{A}'};
M_.endo_names_long(4) = {'AR(1) technology process'};
M_.endo_names(5) = {'N'};
M_.endo_names_tex(5) = {'{N}'};
M_.endo_names_long(5) = {'Hours worked'};
M_.endo_names(6) = {'R'};
M_.endo_names_tex(6) = {'{R^n}'};
M_.endo_names_long(6) = {'Nominal Interest Rate'};
M_.endo_names(7) = {'realinterest'};
M_.endo_names_tex(7) = {'{R^{r}}'};
M_.endo_names_long(7) = {'Real Interest Rate'};
M_.endo_names(8) = {'Y'};
M_.endo_names_tex(8) = {'{Y}'};
M_.endo_names_long(8) = {'Output'};
M_.endo_names(9) = {'nu'};
M_.endo_names_tex(9) = {'{\nu}'};
M_.endo_names_long(9) = {'AR(1) monetary policy shock process'};
M_.endo_names(10) = {'m_growth_ann'};
M_.endo_names_tex(10) = {'{\Delta M}'};
M_.endo_names_long(10) = {'money growth'};
M_.endo_names(11) = {'Q'};
M_.endo_names_tex(11) = {'{Q}'};
M_.endo_names_long(11) = {'Bond price'};
M_.endo_names(12) = {'Z'};
M_.endo_names_tex(12) = {'{Z}'};
M_.endo_names_long(12) = {'AR(1) preference shock process'};
M_.endo_partitions = struct();
M_.param_names = cell(9,1);
M_.param_names_tex = cell(9,1);
M_.param_names_long = cell(9,1);
M_.param_names(1) = {'alppha'};
M_.param_names_tex(1) = {'{\alpha}'};
M_.param_names_long(1) = {'capital share'};
M_.param_names(2) = {'betta'};
M_.param_names_tex(2) = {'{\beta}'};
M_.param_names_long(2) = {'discount factor'};
M_.param_names(3) = {'rho_a'};
M_.param_names_tex(3) = {'{\rho_a}'};
M_.param_names_long(3) = {'autocorrelation technology shock'};
M_.param_names(4) = {'rho_z'};
M_.param_names_tex(4) = {'{\rho_z}'};
M_.param_names_long(4) = {'autocorrelation preference shock'};
M_.param_names(5) = {'rho_nu'};
M_.param_names_tex(5) = {'{\rho_{\nu}}'};
M_.param_names_long(5) = {'autocorrelation monetary policy shock'};
M_.param_names(6) = {'siggma'};
M_.param_names_tex(6) = {'{\sigma}'};
M_.param_names_long(6) = {'log utility'};
M_.param_names(7) = {'varphi'};
M_.param_names_tex(7) = {'{\varphi}'};
M_.param_names_long(7) = {'unitary Frisch elasticity'};
M_.param_names(8) = {'phi_pi'};
M_.param_names_tex(8) = {'{\phi_{\pi}}'};
M_.param_names_long(8) = {'inflation feedback Taylor Rule'};
M_.param_names(9) = {'eta'};
M_.param_names_tex(9) = {'{\eta}'};
M_.param_names_long(9) = {'semi-elasticity of money demand'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 3;
M_.endo_nbr = 12;
M_.param_nbr = 9;
M_.orig_endo_nbr = 12;
M_.aux_vars = [];
M_.Sigma_e = zeros(3, 3);
M_.Correlation_matrix = eye(3, 3);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.learnt_shocks = [];
M_.learnt_endval = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
M_.matched_irfs = {};
M_.matched_irfs_weights = {};
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.ramsey_policy = false;
options_.discretionary_policy = false;
M_.eq_nbr = 12;
M_.ramsey_orig_eq_nbr = 0;
M_.ramsey_orig_endo_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 1 6 18;
 0 7 0;
 0 8 19;
 2 9 0;
 0 10 0;
 3 11 0;
 0 12 0;
 0 13 0;
 4 14 0;
 0 15 0;
 0 16 0;
 5 17 20;]';
M_.nstatic = 6;
M_.nfwrd   = 1;
M_.npred   = 3;
M_.nboth   = 2;
M_.nsfwrd   = 3;
M_.nspred   = 5;
M_.ndynamic   = 6;
M_.dynamic_tmp_nbr = [7; 1; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'FOC Wages, eq. (7)' ;
  2 , 'name' , 'Euler equation eq. (8)' ;
  3 , 'name' , 'Definition nominal interest rate), p. 22 top' ;
  4 , 'name' , 'Production function eq. (12)' ;
  5 , 'name' , 'FOC wages firm, eq. (14)' ;
  6 , 'name' , 'Definition Real interest rate, eq. 22' ;
  7 , 'name' , 'Monetary Policy Rule, p. 26 bottom/eq. (22)' ;
  8 , 'name' , 'Market Clearing, eq. (15)' ;
  9 , 'name' , 'Technology Shock, p.22' ;
  10 , 'name' , 'Preference Shock, p.21' ;
  11 , 'name' , 'Monetary policy shock, (23)' ;
  12 , 'name' , 'Money growth (derived from eq. (11))' ;
};
M_.mapping.C.eqidx = [1 2 8 12 ];
M_.mapping.W_real.eqidx = [1 5 ];
M_.mapping.Pi.eqidx = [2 6 7 12 ];
M_.mapping.A.eqidx = [4 5 9 ];
M_.mapping.N.eqidx = [1 4 5 ];
M_.mapping.R.eqidx = [3 6 7 12 ];
M_.mapping.realinterest.eqidx = [6 ];
M_.mapping.Y.eqidx = [4 8 ];
M_.mapping.nu.eqidx = [7 11 ];
M_.mapping.m_growth_ann.eqidx = [12 ];
M_.mapping.Q.eqidx = [2 3 ];
M_.mapping.Z.eqidx = [2 10 ];
M_.mapping.eps_a.eqidx = [9 ];
M_.mapping.eps_z.eqidx = [10 ];
M_.mapping.eps_nu.eqidx = [11 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.block_structure.time_recursive = false;
M_.block_structure.block(1).Simulation_Type = 3;
M_.block_structure.block(1).endo_nbr = 1;
M_.block_structure.block(1).mfs = 1;
M_.block_structure.block(1).equation = [ 9];
M_.block_structure.block(1).variable = [ 4];
M_.block_structure.block(1).is_linear = false;
M_.block_structure.block(1).NNZDerivatives = 2;
M_.block_structure.block(1).bytecode_jacob_cols_to_sparse = [0 1 ];
M_.block_structure.block(2).Simulation_Type = 3;
M_.block_structure.block(2).endo_nbr = 1;
M_.block_structure.block(2).mfs = 1;
M_.block_structure.block(2).equation = [ 10];
M_.block_structure.block(2).variable = [ 12];
M_.block_structure.block(2).is_linear = false;
M_.block_structure.block(2).NNZDerivatives = 2;
M_.block_structure.block(2).bytecode_jacob_cols_to_sparse = [0 1 ];
M_.block_structure.block(3).Simulation_Type = 1;
M_.block_structure.block(3).endo_nbr = 1;
M_.block_structure.block(3).mfs = 1;
M_.block_structure.block(3).equation = [ 11];
M_.block_structure.block(3).variable = [ 9];
M_.block_structure.block(3).is_linear = true;
M_.block_structure.block(3).NNZDerivatives = 2;
M_.block_structure.block(3).bytecode_jacob_cols_to_sparse = [1 2 ];
M_.block_structure.block(4).Simulation_Type = 6;
M_.block_structure.block(4).endo_nbr = 4;
M_.block_structure.block(4).mfs = 1;
M_.block_structure.block(4).equation = [ 4 8 1 5];
M_.block_structure.block(4).variable = [ 8 1 2 5];
M_.block_structure.block(4).is_linear = false;
M_.block_structure.block(4).NNZDerivatives = 2;
M_.block_structure.block(4).bytecode_jacob_cols_to_sparse = [0 0 0 1 ];
M_.block_structure.block(5).Simulation_Type = 7;
M_.block_structure.block(5).endo_nbr = 3;
M_.block_structure.block(5).mfs = 2;
M_.block_structure.block(5).equation = [ 3 2 7];
M_.block_structure.block(5).variable = [ 6 11 3];
M_.block_structure.block(5).is_linear = false;
M_.block_structure.block(5).NNZDerivatives = 5;
M_.block_structure.block(5).bytecode_jacob_cols_to_sparse = [0 1 2 0 ];
M_.block_structure.block(6).Simulation_Type = 1;
M_.block_structure.block(6).endo_nbr = 1;
M_.block_structure.block(6).mfs = 1;
M_.block_structure.block(6).equation = [ 12];
M_.block_structure.block(6).variable = [ 10];
M_.block_structure.block(6).is_linear = true;
M_.block_structure.block(6).NNZDerivatives = 1;
M_.block_structure.block(6).bytecode_jacob_cols_to_sparse = [2 ];
M_.block_structure.block(7).Simulation_Type = 3;
M_.block_structure.block(7).endo_nbr = 1;
M_.block_structure.block(7).mfs = 1;
M_.block_structure.block(7).equation = [ 6];
M_.block_structure.block(7).variable = [ 7];
M_.block_structure.block(7).is_linear = true;
M_.block_structure.block(7).NNZDerivatives = 1;
M_.block_structure.block(7).bytecode_jacob_cols_to_sparse = [1 ];
M_.block_structure.block(1).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(1).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(1).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(2).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(2).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(2).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(3).g1_sparse_rowval = int32([]);
M_.block_structure.block(3).g1_sparse_colval = int32([]);
M_.block_structure.block(3).g1_sparse_colptr = int32([]);
M_.block_structure.block(4).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(4).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(4).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(5).g1_sparse_rowval = int32([1 2 2 ]);
M_.block_structure.block(5).g1_sparse_colval = int32([1 1 2 ]);
M_.block_structure.block(5).g1_sparse_colptr = int32([1 3 4 ]);
M_.block_structure.block(6).g1_sparse_rowval = int32([]);
M_.block_structure.block(6).g1_sparse_colval = int32([]);
M_.block_structure.block(6).g1_sparse_colptr = int32([]);
M_.block_structure.block(7).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(7).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(7).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.variable_reordered = [ 4 12 9 8 1 2 5 6 11 3 10 7];
M_.block_structure.equation_reordered = [ 9 10 11 4 8 1 5 3 2 7 12 6];
M_.block_structure.incidence(1).lead_lag = -1;
M_.block_structure.incidence(1).sparse_IM = [
 9 4;
 10 12;
 11 9;
 12 1;
 12 6;
];
M_.block_structure.incidence(2).lead_lag = 0;
M_.block_structure.incidence(2).sparse_IM = [
 1 1;
 1 2;
 1 5;
 2 1;
 2 11;
 2 12;
 3 6;
 3 11;
 4 4;
 4 5;
 4 8;
 5 2;
 5 4;
 5 5;
 6 6;
 6 7;
 7 3;
 7 6;
 7 9;
 8 1;
 8 8;
 9 4;
 10 12;
 11 9;
 12 1;
 12 3;
 12 6;
 12 10;
];
M_.block_structure.incidence(3).lead_lag = 1;
M_.block_structure.incidence(3).sparse_IM = [
 2 1;
 2 3;
 2 12;
 6 3;
];
M_.block_structure.dyn_tmp_nbr = 4;
M_.state_var = [4 12 9 1 6 ];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(12, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(3, 1);
M_.params = NaN(9, 1);
M_.endo_trends = struct('deflator', cell(12, 1), 'log_deflator', cell(12, 1), 'growth_factor', cell(12, 1), 'log_growth_factor', cell(12, 1));
M_.NNZDerivatives = [40; -1; -1; ];
M_.dynamic_g1_sparse_rowval = int32([12 9 12 11 10 1 2 8 12 1 5 7 12 4 5 9 1 4 5 3 6 7 12 6 4 8 7 11 12 2 3 2 10 2 2 6 2 9 10 11 ]);
M_.dynamic_g1_sparse_colval = int32([1 4 6 9 12 13 13 13 13 14 14 15 15 16 16 16 17 17 17 18 18 18 18 19 20 20 21 21 22 23 23 24 24 25 27 27 36 37 38 39 ]);
M_.dynamic_g1_sparse_colptr = int32([1 2 2 2 3 3 4 4 4 5 5 5 6 10 12 14 17 20 24 25 27 29 30 32 34 35 35 37 37 37 37 37 37 37 37 37 38 39 40 41 ]);
M_.lhs = {
'W_real'; 
'Q'; 
'R'; 
'Y'; 
'W_real'; 
'R'; 
'R'; 
'C'; 
'log(A)'; 
'log(Z)'; 
'nu'; 
'm_growth_ann'; 
};
M_.static_tmp_nbr = [5; 0; 0; 0; ];
M_.block_structure_stat.block(1).Simulation_Type = 3;
M_.block_structure_stat.block(1).endo_nbr = 1;
M_.block_structure_stat.block(1).mfs = 1;
M_.block_structure_stat.block(1).equation = [ 9];
M_.block_structure_stat.block(1).variable = [ 4];
M_.block_structure_stat.block(2).Simulation_Type = 3;
M_.block_structure_stat.block(2).endo_nbr = 1;
M_.block_structure_stat.block(2).mfs = 1;
M_.block_structure_stat.block(2).equation = [ 10];
M_.block_structure_stat.block(2).variable = [ 12];
M_.block_structure_stat.block(3).Simulation_Type = 3;
M_.block_structure_stat.block(3).endo_nbr = 1;
M_.block_structure_stat.block(3).mfs = 1;
M_.block_structure_stat.block(3).equation = [ 11];
M_.block_structure_stat.block(3).variable = [ 9];
M_.block_structure_stat.block(4).Simulation_Type = 6;
M_.block_structure_stat.block(4).endo_nbr = 3;
M_.block_structure_stat.block(4).mfs = 3;
M_.block_structure_stat.block(4).equation = [ 3 7 2];
M_.block_structure_stat.block(4).variable = [ 11 6 3];
M_.block_structure_stat.block(5).Simulation_Type = 6;
M_.block_structure_stat.block(5).endo_nbr = 4;
M_.block_structure_stat.block(5).mfs = 4;
M_.block_structure_stat.block(5).equation = [ 4 5 8 1];
M_.block_structure_stat.block(5).variable = [ 8 5 1 2];
M_.block_structure_stat.block(6).Simulation_Type = 1;
M_.block_structure_stat.block(6).endo_nbr = 1;
M_.block_structure_stat.block(6).mfs = 1;
M_.block_structure_stat.block(6).equation = [ 12];
M_.block_structure_stat.block(6).variable = [ 10];
M_.block_structure_stat.block(7).Simulation_Type = 3;
M_.block_structure_stat.block(7).endo_nbr = 1;
M_.block_structure_stat.block(7).mfs = 1;
M_.block_structure_stat.block(7).equation = [ 6];
M_.block_structure_stat.block(7).variable = [ 7];
M_.block_structure_stat.variable_reordered = [ 4 12 9 11 6 3 8 5 1 2 10 7];
M_.block_structure_stat.equation_reordered = [ 9 10 11 3 7 2 4 5 8 1 12 6];
M_.block_structure_stat.incidence.sparse_IM = [
 1 1;
 1 2;
 1 5;
 2 3;
 2 11;
 3 6;
 3 11;
 4 4;
 4 5;
 4 8;
 5 2;
 5 4;
 5 5;
 6 3;
 6 6;
 6 7;
 7 3;
 7 6;
 7 9;
 8 1;
 8 8;
 9 4;
 10 12;
 11 9;
 12 3;
 12 10;
];
M_.block_structure_stat.tmp_nbr = 5;
M_.block_structure_stat.block(1).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(1).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(1).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(2).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(3).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(4).g1_sparse_rowval = int32([1 3 1 2 2 3 ]);
M_.block_structure_stat.block(4).g1_sparse_colval = int32([1 1 2 2 3 3 ]);
M_.block_structure_stat.block(4).g1_sparse_colptr = int32([1 3 5 7 ]);
M_.block_structure_stat.block(5).g1_sparse_rowval = int32([1 3 1 2 4 3 4 2 4 ]);
M_.block_structure_stat.block(5).g1_sparse_colval = int32([1 1 2 2 2 3 3 4 4 ]);
M_.block_structure_stat.block(5).g1_sparse_colptr = int32([1 3 6 8 10 ]);
M_.block_structure_stat.block(6).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(6).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(6).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(7).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(7).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(7).g1_sparse_colptr = int32([1 2 ]);
M_.static_g1_sparse_rowval = int32([1 8 1 5 2 6 7 12 4 5 9 1 4 5 3 6 7 6 4 8 7 11 12 2 3 10 ]);
M_.static_g1_sparse_colval = int32([1 1 2 2 3 3 3 3 4 4 4 5 5 5 6 6 6 7 8 8 9 9 10 11 11 12 ]);
M_.static_g1_sparse_colptr = int32([1 3 5 9 12 15 18 19 21 23 24 26 27 ]);
M_.params(1) = 0.25;
alppha = M_.params(1);
M_.params(2) = 0.99;
betta = M_.params(2);
M_.params(3) = 0.9;
rho_a = M_.params(3);
M_.params(4) = 0.5;
rho_z = M_.params(4);
M_.params(5) = 0.5;
rho_nu = M_.params(5);
M_.params(6) = 1;
siggma = M_.params(6);
M_.params(7) = 5;
varphi = M_.params(7);
M_.params(8) = 1.5;
phi_pi = M_.params(8);
M_.params(9) = 3.77;
eta = M_.params(9);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (1)^2;
M_.Sigma_e(2, 2) = (1)^2;
M_.Sigma_e(3, 3) = (1)^2;
options_resid_ = struct();
display_static_residuals(M_, options_, oo_, options_resid_);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 20;
options_.order = 1;
var_list_ = {'Y';'C';'Pi';'R';'realinterest';'m_growth_ann'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'Gali_2015_chapter_2_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Gali_2015_chapter_2_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Gali_2015_chapter_2_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Gali_2015_chapter_2_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Gali_2015_chapter_2_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Gali_2015_chapter_2_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Gali_2015_chapter_2_results.mat'], 'oo_recursive_', '-append');
end
if exist('options_mom_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Gali_2015_chapter_2_results.mat'], 'options_mom_', '-append');
end
disp('Note: 1 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
